"""
Main Application Entry Point
CrewAI-powered application with modular architecture.
"""

import logging
from pathlib import Path
from crewai import Agent, Task, Crew
from langchain_openai import ChatOpenAI
from core.config import (
    BASE_DIR,
    OPENAI_API_KEY,
    LANGCHAIN_API_KEY,
    LANGCHAIN_TRACING_V2,
    LOG_LEVEL,
    DEBUG,
)

# Configure logging
logging.basicConfig(
    level=getattr(logging, LOG_LEVEL),
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler(BASE_DIR / "app.log"),
        logging.StreamHandler()
    ]
)

logger = logging.getLogger(__name__)


def create_llm():
    """
    Create and configure the LLM instance.
    
    Returns:
        ChatOpenAI: Configured language model instance.
    """
    if not OPENAI_API_KEY:
        logger.error("OPENAI_API_KEY is not set in environment variables")
        raise ValueError("OPENAI_API_KEY is required")
    
    return ChatOpenAI(
        model="gpt-4o",
        temperature=0.7,
        api_key=OPENAI_API_KEY,
    )


def create_research_agent(llm):
    """
    Create a research agent for gathering information.
    
    Args:
        llm: Language model instance.
        
    Returns:
        Agent: Configured research agent.
    """
    return Agent(
        role="Senior Research Analyst",
        goal="Conduct thorough research on specified topics and gather comprehensive information",
        backstory="""You are an expert researcher with extensive knowledge in 
        data analysis, market research, and information synthesis. You have a keen eye for 
        details and can quickly identify key insights from large datasets.""",
        verbose=True,
        allow_delegation=False,
        tools=[],
        llm=llm,
    )


def create_writer_agent(llm):
    """
    Create a content writer agent for generating reports.
    
    Args:
        llm: Language model instance.
        
    Returns:
        Agent: Configured writer agent.
    """
    return Agent(
        role="Senior Content Writer",
        goal="Transform research findings into well-structured, engaging content",
        backstory="""You are a skilled writer with expertise in creating professional 
        reports, articles, and documentation. You have a talent for making complex topics 
        accessible and engaging while maintaining accuracy.""",
        verbose=True,
        allow_delegation=False,
        tools=[],
        llm=llm,
    )


def create_analysis_task(research_output, topic: str):
    """
    Create an analysis task based on research output.
    
    Args:
        research_output: Research findings from the research agent.
        topic: The topic to analyze.
        
    Returns:
        Task: Configured analysis task.
    """
    return Task(
        description=f"""Analyze the following research findings about "{topic}":

Research Summary:
{research_output}

Provide a comprehensive analysis including:
1. Key findings and insights
2. Important trends or patterns
3. Potential implications
4. Recommendations based on the data""",
        expected_output="""A detailed analysis report with clear sections for:
- Executive Summary
- Key Findings
- Trends and Patterns
- Implications
- Recommendations

The output should be well-structured, professional, and actionable.""",
        agent=None,  # Will be assigned dynamically
    )


def create_summary_task(analysis_output):
    """
    Create a summary task based on analysis output.
    
    Args:
        analysis_output: Analysis findings from the analysis agent.
        
    Returns:
        Task: Configured summary task.
    """
    return Task(
        description="""Create a concise executive summary of the analysis, highlighting:
1. The most important findings
2. Key recommendations
3. Action items for stakeholders

Keep it under 500 words and make it engaging for business leaders.""",
        expected_output="A compelling executive summary that captures the essence of the analysis in an accessible format.",
        agent=None,  # Will be assigned dynamically
    )


def run_crew(topic: str) -> str:
    """
    Execute the CrewAI crew to generate a report on the given topic.
    
    Args:
        topic: The topic to research and analyze.
        
    Returns:
        str: Final report generated by the crew.
    """
    logger.info(f"Starting crew execution for topic: {topic}")
    
    # Initialize LLM
    llm = create_llm()
    
    # Create agents
    research_agent = create_research_agent(llm)
    writer_agent = create_writer_agent(llm)
    
    # Create tasks
    research_task = Task(
        description=f"Conduct comprehensive research on '{topic}' and gather all relevant information, statistics, and insights.",
        expected_output="A detailed research report with sources, statistics, and key findings about the topic.",
        agent=research_agent,
    )
    
    analysis_task = create_analysis_task(Task.output(research_task), topic)
    summary_task = create_summary_task(analysis_task.output)
    
    # Create crew
    crew = Crew(
        agents=[research_agent, writer_agent],
        tasks=[research_task, analysis_task, summary_task],
        verbose=True,
        process="sequential",
    )
    
    # Execute crew
    result = crew.kickoff()
    
    logger.info("Crew execution completed successfully")
    return str(result)


def main():
    """Main entry point for the application."""
    logger.info("=" * 50)
    logger.info(f"Starting {__name__.split('.')[0]} Application")
    logger.info("=" * 50)
    
    # Validate required environment variables
    if not OPENAI_API_KEY:
        logger.error("OPENAI_API_KEY is not configured. Please set it in your .env file.")
        raise SystemExit(1)
    
    if LANGCHAIN_TRACING_V2 and not LANGCHAIN_API_KEY:
        logger.warning("LANGCHAIN_TRACING_V2 is enabled but LANGCHAIN_API_KEY is not set. Tracing will be disabled.")
    
    # Get topic from command line argument or use default
    import sys
    topic = sys.argv[1] if len(sys.argv) > 1 else "Artificial Intelligence in Healthcare"
    
    try:
        result = run_crew(topic)
        print("\n" + "=" * 50)
        print("FINAL REPORT:")
        print("=" * 50)
        print(result)
        print("=" * 50)
    except Exception as e:
        logger.error(f"Error during crew execution: {str(e)}")
        raise


if __name__ == "__main__":
    main()
